services:
  portfolio-api:
    container_name: portfolio-api
    image: ghcr.io/snow-platform/portfolio-api:${VERSION}
    environment:
      - ConnectionStrings__Main=${POSTGRESQL_MAIN}
    restart: unless-stopped
    cpu_count: 1
    mem_limit: 512M
    mem_reservation: 256M
    networks:
      - proxy

networks:
  proxy:
    external: true
