name: "release: create on push"

on:
  push:
    branches:
      - main

jobs:
  build_n_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '10.0.x'
      - name: restore
        run: dotnet restore
      - name: build
        run: dotnet build --no-restore --configuration Release
      - name: test
        run: dotnet test --no-restore --no-build --configuration Release --verbosity normal

  tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-tags: true
      - name: latest tag
        id: tag
        run: |
          tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "::notice title=Tag:: $tag"
          echo "tag=$tag" >> $GITHUB_OUTPUT
  
  check:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-tags: true
      - name: check release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ needs.tag.outputs.tag }}
        run: |
          if gh release view $TAG; then
            echo "::error::The release $TAG already exists"
            exit 0
          fi
  
  release:
    needs: [ build_n_test, tag, check ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-tags: true
      - name: create release
        env:
          # This requires a PAT because a workflow that is triggered by release cannot run 
          # if the release is created by GITHUB_TOKEN
          GH_TOKEN: ${{ secrets.YUKI_TOKEN }}
          TAG: ${{ needs.tag.outputs.tag }}
        run: |
          gh release create $TAG --generate-notes --verify-tag